sudo: false
language: php
php:
    - 5.6
    - 7
env:
    global:
        - DB=sqlite
    matrix:
        - CORE_BRANCH=stable10
        - CORE_BRANCH=master

matrix:
    fast_finish: true

before_install:
    # install core
    - cd ../
    - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH
    - mv deck-dev server/apps/deck

before_script:
    # fill owncloud with default configs and enable deck
    - cd server 
    - mkdir data
    - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
    - ./occ app:enable deck
    - ./occ app:check-code deck
    - php -S localhost:8080 &
    - cd apps/deck

script:
    - make test

after_failure:
    - cat ../../data/nextcloud.log

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 49bdd1ee-6ef5-47b9-b80f-825b51515ce9
