[package]
exclude = [
    "build/",
    ".git",
    "js/tests",
    "js/node_modules",
    "tests",
    ".codecov.yml",
    "composer.json",
    "composer.lock",
    "_config.yml",
    ".drone.yml",
    ".eslintignore",
    ".eslintrc.yml",
    ".gitignore",
    "issue_template.md",
    "krankerl.toml",
    "Makefile",
    "run-eslint.sh"
]

before_cmds = [
    'make clean-build',
    'make build'
]
